name: 'Publish bicep module'
description: 'Publish bicep module'

inputs:
  moduleFile:
    description: 'Path to the bicep module file to publish'
    required: true
  targetRegistry: 'Azure Container Registry'
    required: true
  targetPath:
    required: true
  moduleVersion:
    required: false
    default: latest
    type: string

runs:
  using: 'composite'
  steps:
    - name: 'Deploy modules'
      run: |
        az bicep install
        az bicep publish --file ${{ inputs.moduleFile }} --target br:${{ inputs.targetRegistry }}/${{ inputs.targetPath }}:${{ inputs.moduleVersion }}
