name: 'Publish bicep module'
description: 'Publish bicep module'

inputs:
  moduleFile:
    description: 'Path to the bicep module file to publish'
    required: true
    type: string
  targetRegistry: 'Azure Container Registry'
    description: 'fqdn of the target Azure Container Registry'
    required: true
    type: string
  targetPath:
    description: 'Target repository path'
    required: true
    type: string
  moduleTag:
    description: 'Module tag'
    required: false
    default: 'latest'
    type: string

runs:
  using: 'composite'
  steps:
    - name: 'Deploy modules'
      run: |
        az bicep install
        az bicep publish --file ${{ inputs.moduleFile }} --target br:${{ inputs.targetRegistry }}/${{ inputs.targetPath }}:${{ inputs.moduleTag }}
