name: 'AKS'

on:
  workflow_dispatch:
    inputs:
      moduleTag:
        description: 'Module tag'
        required: false
        default: 'latest'
        type: string

  push:
    branches:
      - main
    paths:
      - modules/aks/**
      - .github/workflows/azurekubernetesservice.yml
    # tags:
    #   - v*

permissions:
      id-token: write
      contents: read

defaults:
  run:
    shell: bash

jobs:
  # dump_contexts_to_log:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       id: github_context_step
  #       run: echo '${{ toJSON(github) }}'
  #     - name: Dump job context
  #       run: echo '${{ toJSON(job) }}'
  #     - name: Dump steps context
  #       run: echo '${{ toJSON(steps) }}'
  #     - name: Dump runner context
  #       run: echo '${{ toJSON(runner) }}'
  #     - name: Dump strategy context
  #       run: echo '${{ toJSON(strategy) }}'
  #     - name: Dump matrix context
  #       run: echo '${{ toJSON(matrix) }}'

  deploy:
    name: 'Publish Azure Kubernetes Service modules'
    runs-on: ubuntu-latest
    #environment: Microsoft
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Azure cli login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: 'Publish module - (AKS - Public, CNI, RBAC) - tag'
      if: github.ref_type == 'tag'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/aks/public-cni-rbac.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/aks.public.cni.rbac'
        moduleTag: github.ref_name

    - name: 'Publish module - (AKS - Public, CNI, RBAC) - main branch'
      if: github.ref_type != 'tag' && github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/aks/public-cni-rbac.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/aks.public.cni.rbac'
        moduleTag: 'latest'

    - name: 'Publish module - (AKS - Public, CNI, RBAC) - manual'
      if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/aks/public-cni-rbac.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/aks.public.cni.rbac'
        moduleTag: inputs.moduleTag