name: 'Container Registry'

on:
  workflow_dispatch:
    inputs:
      moduleTag:
        description: 'Module tag'
        required: false
        default: 'latest'
        type: string

  push:
    branches:
      - main
    paths:
      - modules/acr/**
      - .github/workflows/containerregistry.yml
    tags:
      - v*

permissions:
      id-token: write
      contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: 'Publish Azure Container Registry module'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Azure cli login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: 'Publish module'
      if: github.ref_type == 'tag'&& github.ref == 'refs/heads/main'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/acr/standard.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/acr.standard'
        moduleTag: '${{ github.ref_name }}'

    - name: 'Publish module'
      if: github.ref_type != 'tag' && github.ref == 'refs/heads/main'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/acr/standard.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/acr.standard'
        moduleTag: 'latest'

    - name: 'Publish module'
      if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/acr/standard.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/acr.standard'
        moduleTag: ${{ inputs.moduleTag }}