name: 'Container Registry'

on:
  workflow_dispatch:
    inputs:
      moduleTag:
        description: 'Module tag'
        required: false
        default: 'latest'
        type: string

  push:
    branches:
      - main
    paths:
      - modules/acr/**
      - .github/workflows/containerregistry.yml
    tags:
      - v*

permissions:
      id-token: write
      contents: read

defaults:
  run:
    shell: bash

jobs:
#   dump_contexts_to_log:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         id: github_context_step
#         run: echo '${{ toJSON(github) }}'
#       - name: Dump job context
#         run: echo '${{ toJSON(job) }}'
#       - name: Dump steps context
#         run: echo '${{ toJSON(steps) }}'
#       - name: Dump runner context
#         run: echo '${{ toJSON(runner) }}'
#       - name: Dump strategy context
#         run: echo '${{ toJSON(strategy) }}'
#       - name: Dump matrix context
#         run: echo '${{ toJSON(matrix) }}'

  deploy:
    name: 'Publish Azure Container Registry module'
    runs-on: ubuntu-latest
    environment: Microsoft
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Azure cli login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: 'Publish module - tag'
      if: github.ref_type == 'tag'&& github.ref == 'refs/heads/main'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/acr/standard.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/acr.standard'
        moduleTag: github.ref_name

    - name: 'Publish module - main branch'
      if: github.ref_type != 'tag' && github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/acr/standard.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/acr.standard'
        moduleTag: 'latest'

    - name: 'Publish module - manual'
      if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
      uses: ./.github/templates/publishmodule
      with:
        moduleFile: 'modules/acr/standard.bicep'
        targetRegistry: '${{ secrets.REGISTRY }}'
        targetPath: 'bicep/modules/acr.standard'
        moduleTag: inputs.moduleTag