name: 'Container Registry'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    name: 'Publish bicep module'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Azure cli login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: 'Run az commands'
      run: |
        az bicep install
        az bicep publish --file modules/acr/standard.bicep --target br:${{ secrets.REGISTRY }}/bicep/modules/acr.standard:latest