name: 'Container Registry'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - modules/acr/**
      - .github/workflows/containerregistry.yml

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    name: 'Publish Azure Container Registry module'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Azure cli login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: 'Publish module'
        uses: ./.github/actions/templates/publishmodule
        with:
          modulePath: modules/acr/standard.bicep
          targetRegistry: ${{ secrets.REGISTRY }}
          targetPath: bicep/modules/acr.standard
          moduleVersion: latest
